### ISSUE TITLE
[issue]Unable to chat/无法聊天

### ISSUE THREAD

**Issue by DavidBlackCN** [alex3236/ItemChat#2]
### Bug description

I tried to use this mod in my  modpack(server), but the player  sent the message without any response.
我尝试将此mod用于我的整合包（服务端）中，但玩家在聊天栏输入文字后发送没有任何回应。

Minecraft=1.19.2
Mod=ItemChat v1.0.0 for mc1.19.4

More: The command execution is normal,only the chat encountered issues.
补充：指令执行正常，只有聊天出现了问题。

The server output:
服务端输出如下：

> [16:58:37] [Server thread/ERROR]: Chain link failed, continuing to next one
java.lang.NoSuchMethodError: 'net.minecraft.class_2561 net.minecraft.class_7471.method_46291()'
	at net.minecraft.class_3324.handler$dkf000$item_chat$onBroadcast(class_3324.java:10522) ~[server-intermediary.jar:?]
	at net.minecraft.class_3324.method_43673(class_3324.java) ~[server-intermediary.jar:?]
	at net.minecraft.class_3244.method_44155(class_3244.java:1444) ~[server-intermediary.jar:?]
	at net.minecraft.class_3244.method_45064(class_3244.java:1302) ~[server-intermediary.jar:?]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
	at net.minecraft.class_3738.run(class_3738.java:18) ~[server-intermediary.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:157) ~[server-intermediary.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:776) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:159) ~[server-intermediary.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:131) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:758) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:752) ~[server-intermediary.jar:?]
	at net.minecraft.class_1255.method_5383(class_1255.java:116) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:736) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.handler$zio000$carpet$modifiedRunLoop(MinecraftServer.java:4394) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:644) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257) ~[server-intermediary.jar:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]

I don't know where the problem is,or a conflict with a mod in the modpack
我不知道问题出现在哪里，是否是和整合包里的某个mod冲突

I would greatly appreciate it if someone could find the problem or fix the bug!
如果能找到问题所在或是修复该bug我将十分感激！

### Steps to reproduce

1.Create a new world
2.Player send random messages
3.bug

### Minecraft version

1.19.2

### ItemChat version

v1.0.0 for mc1.19.4

### Check list

- [X] I have verified that the issue persists in the latest version of the mod.
- [X] I have searched the existing issues and confirmed that this is not a duplicate.

**Comment by alex3236** [comment]
请尝试在不添加其他 Mod 的情况下能否复现

**Comment by alex3236** [comment]
closing since there's almost 1yr
